### ISSUE TITLE
Nothing Appears on the Screen When in the `GameScene` View

### ISSUE THREAD

**Issue by NobbZ** [indiv0/colonize#81]
There is the screenshot in the README.md, displaying much of colors.

Locally I do only see gray, a little bit of red and black letters:

![nothing_2_see](https://cloud.githubusercontent.com/assets/58951/15284668/f7a9a5e0-1b52-11e6-99de-3982ad6ea77f.png)

I compiled using the following environment:

| **component** | **version** |
|---|---|
| OS | Ubuntu Linux 14.04 LTS |
| `rustc` | stable-x86_64-unknown-linux-gnu<br />rustc 1.8.0 (db2939409 2016-04-11) |
| graphic card | Some Intel onboard stuff, shared memory, up to 512 MiB of Video-RAM |
| Memory | 8 GiB |
| CPU | i5 @ 2600 GHz |
| more needed? | will add… |

**Comment by indiv0** [comment]
Yeah, I should make this more obvious.

Basically, the camera starts you at position `[0, 0, 0]`, however, the terrain generation algorithm results in the ground being higher than that point (around `[0, 16, 0]`, I think).

So you need to move the camera up along the Y-axis to get higher (you're basically "inside" the ground right now).

They key for that is either `,` or `.`

I should probably make the camera start above the ground though as a more proper solution.

**Comment by indiv0** [comment]
This should be fixed on master with #85 now.

**Comment by NobbZ** [comment]
Yeah, seems to work now.
